---
output:
  # General Latex arguments
  bookdown::pdf_document2:
    toc           : false
    keep_tex      : true
    fig_caption   : true
    latex_engine  : pdflatex
    number_section: true

  # # General Word arguments
  # bookdown::word_document2:
  #   toc          : false
  #   reference_doc: "default"

# Latex arguments
header-includes:
  - \usepackage{float}
  - \usepackage{tikz}
  - \usepackage{setspace}
  # - \onehalfspacing

fancy_lists : true
fig_caption : yes
starnum     : true
---

# Active and Passive Transparency in Brazilian Municipalities {#title3}

## Summary

An important part of government accountability is the obligation of public officials to inform and explain their actions [@SchedlerConceptualizingAccountability2012; @BovensAnalysingAssessingAccountability2007]. In this paper, I propose and analyze two related forms of government accountability: *active transparency*, in which government actively reveals policy information via intra-government auditing and monitoring, and *passive transparency*, in which government passively reveals information through freedom of information (FOIA) requests. Using a natural two-by-two factorial experiment design in Brazilian municipalities between 2006 and 2017, I measure the effects of active and passive transparency on government performance, sanctions, corruption, and transparency outcomes.

## Main Research Question

Does passive transparency contribute anything else beyond active transparency in improving government performance and increasing the number of sanctions applied for government wrongdoing?

## Hypotheses

#. *Active transparency* measures unconditionally improve performance and increase the number of individual and company-wide sanctions.

#. *Passive transparency* only marginally improves performance and increases sanctions when *active transparency* policies are in place.

#. In the absence of *active transparency* measures, *passive transparency* has no effect on improving performance and does not increase the number of sanctions for individuals and companies found guilty of any wrongdoing.

## Outcomes

#. Performance (across all groups):

    #. number of online or in-person services available to the public.
    
    #. the existence of municipal development plan.

#. Sanctions (across all groups):
    
    #. whether the municipality had any public official convicted/fired for wrongdoing.
    
    #. whether local companies have been entered into blacklist of government providers.
    
    #. whether the municipality was targeted by Federal Police in corruption crackdowns.

#. Corruption (across passive transparency groups):
  
    #. corruption findings over total investigations. 
  
    #. amount potentially lost to corruption over the total amount investigated.

#. Transparency (across active transparency groups):

    #. whether the municipality responded in time to four FOIA requests.
    
    #. whether the municipality provided correct answers to four FOIA requests.

## Identification Strategy

Natural experiment coming from the combination of two simultaneous exogenous shocks: randomized audits (active transparency) plus the nationwide implementation of the freedom of information act in 2012 (passive transparency). Municipalities fall into one of three treatments or one control group: audit after FOIA (active and passive transparency), audit before FOIA (active transparency), non-audit after FOIA (passive transparency), and non-audit before FOIA (control).

## Data

Socioeconomic factors and policy outcomes from the National Statistics Office (IBGE); Random audits and transparency measures from two programs run by the Office of the Comptroller-General (CGU); Sanctions for individuals and companies and crackdowns from CGU; Convictions from the National Council of Justice (CNJ).

## Contribution and Literature

First paper providing disaggregated evidence for the effect of passive transparency (FOIA) in development settings; paper advances theory by breaking transparency into active and passive arms; new transparency dataset and innovative research design.