---
output:
  # General Latex arguments
  bookdown::pdf_document2:
    toc           : false
    keep_tex      : true
    fig_caption   : true
    latex_engine  : pdflatex
    number_section: true

  # # General Word arguments
  # bookdown::word_document2:
  #   toc          : false
  #   reference_doc: "default"

# Latex arguments
header-includes:
  - \usepackage{float}
  - \usepackage{tikz}
  - \usepackage{setspace}
  # - \onehalfspacing

fancy_lists : true
fig_caption : yes
starnum     : true
---

# Judicial Favoritism of Politicians: Evidence from Small Claim Courts {#title2}

## Summary

Judicial favoritism has long been a subject of research in law, economics, and political science. However, scholars have mainly focused on gender and ethnicity bias but have largely ignored whether judges treat politicians in the same way as ordinary citizens. I use a unique dataset of judicial decisions in small claims courts in the state of São Paulo, Brazil, where cases are assigned to judges at random, to verify whether local politicians have a higher winning rate against other plaintiffs or defendants. Under judicial independence, politicians should have the same win rate at trial than any other citizen.

## Main Research Question

Are politicians more likely to receive favorable rulings in small claim courts?

## Hypotheses

#. Politicians have a higher winning rate at the trial stage in small court claims against their counterparts.

#. In cases where claims are of higher monetary value, politicians should see an even larger winning rate than at cases of lower value.

#. Proximity to elections increases the winning rates for politicians on the campaign trail.

## Outcomes

#. Whether politicians have had the case ruled in their favor.

#. The amount awarded to (or avoided by) politicians in small claim court cases.

## Identification Strategy

Natural Experiment. State Courts assign cases at random when the judicial district has more than one judge on the bench. I combine empirical strategies in @ShayoJudicialIngroupBias2011, @AbramsJudgesVaryTheir2012, and @Sanchez-MartinezDismantlingInstitutionsCourt2018 to test random assignment and provide robustness checks against potential spurious relationships between being a politician and having a favorable court outcome.

## Data

São Paulo State Court (TJ-SP) rulings involving candidates running for office in the State of São Paulo between 2010-2016 electoral cycles. Judicial district, judge and politicians' individual characteristics from the TJ-SP, Electoral Court (TSE), and the National Statistics Office (IBGE).

## Contribution to Literature

It is amongst the new, few papers to investigate judicial bias for individual politicians and it contributes to the literature on the benefits of political connectedness.